controllers/SiteController.php
<?php

namespace app\controllers;

use app\entities\Author;
use app\entities\Book;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function actionAuthor()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Author::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('author', ['dataProvider' => $dataProvider]);
    }


    public function actionBook()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Book::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('book', ['dataProvider' => $dataProvider]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Авторы', 'url' => ['/site/author']],
            ['label' => 'Книги', 'url' => ['/site/book']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_author-list.php
<?php

/**
 * @var \app\entities\Author $model
 */

use \yii\helpers\ArrayHelper;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $model->name; ?></h3>
    </div>
    <div class="panel-body">
        <?= implode(',', ArrayHelper::getColumn($model->authorBooks, 'name')); ?>
    </div>
</div>

views/site/_book-list.php
<?php

use \yii\helpers\ArrayHelper;

/**  @var \app\entities\Book $model */

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $model->name; ?></h3>
    </div>
    <div class="panel-body">
        <?= implode(',', ArrayHelper::getColumn($model->bookAuthors, 'name')); ?>
    </div>
</div>

views/site/author.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;

/** @var \yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Авторы';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="site-author">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= ListView::widget(['dataProvider' => $dataProvider, 'itemView' => '_author-list']); ?>
</div>

views/site/book.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;

/**  @var \yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Книги';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-book">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= ListView::widget(['dataProvider' => $dataProvider, 'itemView' => '_book-list']); ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>